### ISSUE TITLE
[feature] route tracker, 경로로 객체 이동시키기

### ISSUE THREAD

**Issue by sjmin-gaia3d** [sjmin-gaia3d/cesium-openlayers#8]
## route tracker, 경로로 객체 이동시키기

> 생성된 객체(Polygon)를 Polyline/LineString을 따라 이동시킨다.

## 작업 상세 내용

- [ ] cesium 객체 이동시키기
- [ ] openlayers 객체 이동시키기
- [ ] 이동하는 객체에 시점 고정하기

## 참고할만한 자료(선택)
https://cesium.com/learn/cesiumjs-learn/cesiumjs-flight-tracker/
